### ISSUE TITLE
Have examples directory, build and push emdaer-examples repository

### ISSUE THREAD

**Issue by flipactual** [emdaer/emdaer#42]
An `examples/` directory in the monorepo which demonstrates constructing files via emdaer in both yml and JavaScript and pushes the built files to `emdaer/emdaer-examples` when we publish a package update would be _choice_

- [ ] add `examples/`
- [ ] build examples when running other validations
- [ ] programmatically ensure examples yield correct results (yay e2e tests)
- [ ] push examples to `emdaer/emdaer-examples` when publishing emdaer via lerna

**Comment by flipactual** [comment]
@infiniteluke considering moving this out of https://github.com/emdaer/emdaer/projects/1, thoughts?
